### ISSUE TITLE
Adding compatibility with new weapon bases

### ISSUE THREAD

**Issue by FgCaboose** [GamerGambit/cw2-fas2-weapon-attachment-vendor#3]
Wondering if it's at all possible to add new weapon bases to your addon. Ik it's a really old one, and this wont most likely get looked at. But I figured I'd ask.

**Comment by GamerGambit** [comment]
Hi, this should be possible. Is there a new weapon add on pack you would like support for or is this a custom one you have made?

**Comment by FgCaboose** [comment]
Really surprised anyone got back lol. Been trying to struggle through with this myself, but im a hella noob to lua. 💀  The weapon base im trying to incorporate is actually an open source gmod workshop addon called ArcCW. A derivative of CW2.0 I believe. 

https://steamcommunity.com/workshop/filedetails/?id=2131057232

**Comment by FgCaboose** [comment]
If you could add support, it'd be an absolute god-sent. Ik a lot of people are looking for support on trying to do so with this addon / looking for a custom one to do the same thing.

**Comment by GamerGambit** [comment]
No problem. I'll see if I have time to check this out later today.

**Comment by FgCaboose** [comment]
That'd be absolutely amazing!

**Comment by GamerGambit** [comment]
I've managed to get the bulk of it working, however it seems that ArcCW doesn't do things the way that FAS and CW2 do. The major one being that ArcCW doesn't have any sense of ownership over attachments so checking if a player has a particular attachment doesn't make sense or exist.

I'll need to write a custom backend to make this work so it might be another day or 2.

**Comment by FgCaboose** [comment]
You'd be the absolute goat if you'd be able to do that. Like 1000000%! Thank you so much for looking into this, really hard to find help for gmod now a days - specially as some one new to lots of lua.

**Comment by GamerGambit** [comment]
Upon further investigation it turns out I was incorrect about ArcCW having no ownership so I didn't need to roll my own ownership system for it. I'm going to push some changes that work as far as I have tested. I realized that the vendor doesn't offer an option to buy secondary ammo which I should add.

**Comment by FgCaboose** [comment]
Oh awesome! I'll def take a look as to what you've added

**Comment by FgCaboose** [comment]
It works! Really looks great, and is gona add a tone of viability to the server im working on. I'll be 10000% sure to let them know who made it, and to give you a look over if you have any GmodStore scripts ^^.

Only thing it does so far is just make a Attachment Vendor: A price of $100 is being used for invalid attachment "fml_mw2r_optic_acog". (x2)
 pop up in bottom left, but im sure I could even just edit that on my own side. Now all I gotta do is get a Db up so it saves what you buy

**Comment by GamerGambit** [comment]
The pricing error is because you haven't set a price for the attachments. You can add the attachment here https://github.com/GamerGambit/cw2-fas2-weapon-attachment-vendor/blob/master/lua/attachment_vendor/configs/sh_attachment_vendor_config.lua#L50 or just add `ATTACHMENT_VENDOR.prices.fml_mw2r_optic_acog = 1337` to your shared code. I could probably add a way to dump all the attachments that don't have prices though.

For the database, the addon comes with sqlite support although it hasn't been tested in years. `ATTACHMENT_VENDOR.persistent = true` in your server code should enable this.

**Comment by FgCaboose** [comment]
Yea I saw that bit of code, so I'll def set it up there. Was just curious bc for some reason the attachments do already have some preset prices lmao. As for the sqlite thingy, I'll probs test it out here pretty soon. 

Thanks again for doing the additional weapon base. It helps a ton

**Comment by GamerGambit** [comment]
When I originally sold this addon years ago I thought it was a good idea to have it not spew out pricing errors so I manually populated the pricing list with all CW2/FAS attachments, but I might change it to just log on startup instead.

**Comment by GamerGambit** [comment]
Just pushed some changes that address attachments that have no price or are marked as obsolete. Turns out there was actually a config option to disable it printing to clients but I just removed the entire thing and it just prints it all at start up.
